name: Check ShopVNB Stock Every 15 Minutes

on:
  schedule:
    - cron: "*/1 * * * *"  # chạy mỗi 1 phút
  workflow_dispatch:        # cho phép chạy thủ công

jobs:
  check-stock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run stock checker
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          ALERT_EMAIL: ${{ secrets.ALERT_EMAIL }}
        run: python check_stock_shopvnb.py 